namespace: "pumpkin"
name: "firedancer"
version: "0.0.1"
readme: "README.md"
description: "Installs/upgrades the firedancer validator"
authors:
    - "Blake Bartenbach <blakebartenbach@gmail.com>"
dependencies:
    "other_namespace.collection1": ">=1.0.0"
    "other_namespace.collection2": ">=2.0.0,<3.0.0"
    "anderson55.my_collection": "*"    # note: "*" selects the highest version available
license:
    - "MIT"
repository: "https://git.sr.ht/~bartenbach/firedancer-ansible"
